### ISSUE TITLE
Make autonomous command to grab a ball and score

### ISSUE THREAD

**Issue by cadenmr** [TeamCautionRobotics/2022-FRC-robot#8]
Grab a second ball from the field, go to the goal and shoot. We ideally need two commands, one for ball 1 and another for ball 2. ([See image](https://imgur.com/a/jAu8z2b))

- The ball output is at the front, intake at the back.
- The bot will be positioned directly in front of the relevant ball. The bumper will be one foot behind the outer tarmac line.
- The bot will be positioned such that, if it were to drive directly backwards, the ball would be in the center of the intake.
- For ball intake and shooting routines, mimic the behavior of commands GrabBall and ShootBall
- Running the shooting routine for 5 seconds should be sufficient

**Comment by docprofsky** [comment]
![ball position diagram](https://user-images.githubusercontent.com/6558271/157350731-6573d370-9e1d-4071-ae8e-2822cffa8e38.png)
Embedding the image because this is slightly more convenient.
